### ISSUE TITLE
Redux connected containers should not be rendered in a component

### ISSUE THREAD

**Issue by vutran** [DextApp/dext#35]
This makes it difficult to write some snapshot tests.

**_Reference:**_ `<ResultList />` produces children contained of `<ResultItemContainer />` which is connected to a redux store.

Will keep this open for discussion on what options are available aside from a single root-level connected container.

**Comment by vutran** [comment]
One way is to just wrap it in a `<Provider>` with a fake store. ([reference](https://twitter.com/dan_abramov/status/772284903425662976))

**Comment by adnasa** [comment]
I just discovered this and I consider it not only an anti-pattern but a bad case of mix of concerns haha

**Comment by vutran** [comment]
I think this can be closed since we're moving away from `redux` anyways

**Comment by adnasa** [comment]
hmmm... let's see how well removing `redux` goes first before we make hasty moves
