### ISSUE TITLE
Friendlier deprecation notices

### ISSUE THREAD

**Issue by vutran** [DextApp/dext#90]
With the introduction of #88 , we'll need to have friendly deprecation notices. Let's use this ticket to see what we want for future alerts of this type.

Ideally, I'd like to see something like [create-react-app](https://github.com/facebookincubator/create-react-app).

**Comment by adnasa** [comment]
I'm not sure how useful this is,
from my POV, this app is still on early stage of development and is not mature enough to display deprecation notices.

**Comment by adnasa** [comment]
This is not interesting right now.
with 2.0 on the map, we will introduce heaps of breaking changes, so I say we address this when we get there
